FROM ruby:2.3.1-slim

RUN apt-get update && apt-get install -y \
      nodejs

RUN mkdir -p /tar_archives /app /bundle
COPY tar_archives /tar_archives
RUN tar -xzf /tar_archives/bundle.tar.gz -C /
RUN tar -xzf /tar_archives/app.tar.gz -C /

WORKDIR /app
ENV BUNDLE_PATH /bundle

# only for persisting group setting
RUN bundle install --without development test

CMD bundle exec rails s -b 0.0.0.0
